const db = {
    "Mathematics": [
        { q: "Calculate the value of N in the following equation using the order of operations: 5 + (3 × 4) - 2 = N.", opts: ["N is equal to 15", "N is equal to 10", "N is equal to 17", "N is equal to 20"], a: 0, expl: "Using PEMDAS (Parentheses, Exponents, Multiplication/Division, Addition/Subtraction): First, multiply 3 × 4 to get 12. Then, add 5 + 12 to get 17. Finally, subtract 17 - 2 to get 15." },
        { q: "Which of the following fractions is equivalent to the decimal number 0.75?", opts: ["1/2 (One half)", "3/4 (Three quarters)", "3/5 (Three fifths)", "7/5 (Seven fifths)"], a: 1, expl: "The decimal 0.75 is equal to 75/100. Simplifying this fraction by dividing both numerator and denominator by 25 gives 3/4." },
        { q: "What is the perimeter of a rectangle that has a length of 10cm and a width of 5cm?", opts: ["30 cm", "50 cm", "15 cm", "25 cm"], a: 0, expl: "The formula for Perimeter is P = 2(Length + Width). P = 2(10 + 5) = 2(15) = 30 cm." },
        { q: "Calculate 25% of the number 200.", opts: ["25", "50", "75", "100"], a: 1, expl: "To find 25% of 200, multiply 200 by 0.25 (or divide by 4). 200 × 0.25 = 50." },
        { q: "Solve the addition of fractions: 1/2 + 1/4. What is the sum?", opts: ["3/4", "2/4", "1/8", "1/6"], a: 0, expl: "Convert 1/2 to 2/4 so they have a common denominator. Then, 2/4 + 1/4 equals 3/4." },
        { q: "Which of the following numbers is exactly divisible by 3?", opts: ["10", "13", "15", "20"], a: 2, expl: "A number is divisible by 3 if the sum of its digits is divisible by 3. For 15: 1 + 5 = 6, and 6 is divisible by 3." },
        { q: "What is the Greatest Common Factor (GCF) of the numbers 12 and 18?", opts: ["3", "6", "9", "12"], a: 1, expl: "Factors of 12 are 1, 2, 3, 4, 6, 12. Factors of 18 are 1, 2, 3, 6, 9, 18. The largest common factor is 6." },
        { q: "Convert the decimal number 3.5 into a mixed number.", opts: ["3 1/2", "3 1/5", "3 1/4", "3 3/5"], a: 0, expl: "The .5 decimal represents one half (1/2). So, 3.5 is equal to 3 1/2." },
        { q: "Calculate the area of a square with a side length of 6 cm.", opts: ["24 square cm", "12 square cm", "36 square cm", "30 square cm"], a: 2, expl: "The Area of a square is side × side. 6 × 6 = 36 square cm." },
        { q: "If the variable x is equal to 5, what is the value of the expression 2x + 3?", opts: ["10", "13", "8", "15"], a: 1, expl: "Substitute 5 for x: 2(5) + 3. This means 10 + 3, which equals 13." },
        { q: "Which of these integers is greater than -5?", opts: ["-10", "-6", "-8", "-1"], a: 3, expl: "On a number line, -1 is to the right of -5, making it a greater value (closer to zero)." },
        { q: "What is the ratio of 4 apples to 8 bananas in simplest form?", opts: ["2:1", "1:2", "4:8", "1:4"], a: 1, expl: "The ratio is 4:8. Dividing both sides by 4 gives the simplified ratio of 1:2." },
        { q: "Subtract 3.45 from 10. (10 - 3.45)", opts: ["6.55", "7.55", "6.65", "7.45"], a: 0, expl: "Align the decimals: 10.00 - 3.45 equals 6.55." },
        { q: "How many centimeters are there in 2 meters?", opts: ["20 cm", "200 cm", "2000 cm", "0.2 cm"], a: 1, expl: "There are 100 centimeters in 1 meter. So, 2 meters = 2 × 100 = 200 cm." },
        { q: "What is the volume of a cube with an edge length of 3 cm?", opts: ["9 cubic cm", "18 cubic cm", "27 cubic cm", "12 cubic cm"], a: 2, expl: "Volume of a cube is edge × edge × edge. 3 × 3 × 3 = 27." },
        { q: "Which of the following numbers is a Prime Number?", opts: ["9", "15", "21", "2"], a: 3, expl: "A prime number has only two factors: 1 and itself. 2 is the only even prime number." },
        { q: "Round the number 45,678 to the nearest thousand.", opts: ["45,000", "46,000", "50,000", "45,700"], a: 1, expl: "The digit in the hundreds place is 6, which is 5 or greater, so we round up the thousands digit. 45 becomes 46." },
        { q: "The number 15 is what percentage of 60?", opts: ["25%", "20%", "50%", "10%"], a: 0, expl: "15 divided by 60 is 1/4. 1/4 as a percentage is 25%." },
        { q: "Multiply the decimals: 0.5 x 0.2", opts: ["1.0", "0.1", "0.01", "0.25"], a: 1, expl: "5 × 2 = 10. There are two decimal places in total (one in each number), so the answer is 0.10 or 0.1." },
        { q: "What is the sum of all interior angles in any triangle?", opts: ["90 degrees", "180 degrees", "360 degrees", "100 degrees"], a: 1, expl: "The sum of the interior angles of any triangle is always 180 degrees." },
        { q: "Supplementary angles add up to how many degrees?", opts: ["90 degrees", "180 degrees", "360 degrees", "45 degrees"], a: 1, expl: "Supplementary angles always sum to 180 degrees." },
        { q: "Complementary angles add up to how many degrees?", opts: ["90 degrees", "180 degrees", "360 degrees", "45 degrees"], a: 0, expl: "Complementary angles always sum to 90 degrees." },
        { q: "What does the metric prefix 'centi-' mean?", opts: ["100", "1/100 (One hundredth)", "1000", "1/1000 (One thousandth)"], a: 1, expl: "Centi means one hundredth (1/100), like in centimeter." },
        { q: "What does the metric prefix 'kilo-' mean?", opts: ["100", "1/100 (One hundredth)", "1000", "1/1000 (One thousandth)"], a: 2, expl: "Kilo means one thousand (1000), like in kilometer." },
        { q: "What is the square root of 81?", opts: ["8", "9", "7", "6"], a: 1, expl: "9 times 9 equals 81, so the square root of 81 is 9." },
        { q: "What is the value of 3 squared (3²)?", opts: ["6", "9", "12", "3"], a: 1, expl: "3 squared means 3 × 3, which equals 9." },
        { q: "What is the reciprocal of the fraction 2/3?", opts: ["3/2", "2/3", "1/3", "4/3"], a: 0, expl: "To find the reciprocal, flip the numerator and denominator. 2/3 becomes 3/2." },
        { q: "Find the Least Common Multiple (LCM) of 4 and 5.", opts: ["10", "20", "15", "25"], a: 1, expl: "Multiples of 4: 4, 8, 12, 16, 20. Multiples of 5: 5, 10, 15, 20. The first match is 20." },
        { q: "What is the simplest form of the fraction 10/20?", opts: ["1/2", "2/4", "5/10", "1/5"], a: 0, expl: "Divide both numerator and denominator by their greatest common divisor (10). 10÷10=1, 20÷10=2. Result is 1/2." },
        { q: "Convert the fraction 1/4 into a decimal.", opts: ["0.5", "0.25", "0.75", "0.4"], a: 1, expl: "1 divided by 4 is 0.25." },
        { q: "Calculate 20% of the number 50.", opts: ["10", "20", "5", "15"], a: 0, expl: "20% is 0.20. 50 × 0.20 = 10." },
        { q: "How many vertices does a triangle have?", opts: ["3 vertices", "4 vertices", "5 vertices", "6 vertices"], a: 0, expl: "A triangle has 3 corners or vertices." },
        { q: "How many faces does a cube have?", opts: ["4 faces", "6 faces", "8 faces", "12 faces"], a: 1, expl: "A cube has 6 flat faces (top, bottom, and 4 sides)." },
        { q: "Which formula is used to find the Area of a Circle?", opts: ["2πr", "πr² (Pi r squared)", "L × W", "½bh"], a: 1, expl: "The Area of a circle is calculated using πr²." },
        { q: "Which formula is used to find the Circumference of a Circle?", opts: ["2πr (2 Pi r)", "πr²", "bh", "s²"], a: 0, expl: "The Circumference is the distance around the circle, calculated using 2πr or πd." },
        { q: "Which of the following is an Odd Number?", opts: ["2", "4", "7", "10"], a: 2, expl: "7 cannot be divided by 2 evenly, so it is an odd number." },
        { q: "Which unit is commonly used to measure the volume of liquid (like water)?", opts: ["Gram", "Liter", "Meter", "Second"], a: 1, expl: "Liters differ from grams (mass) and meters (distance) by measuring volume." },
        { q: "How many years are there in a decade?", opts: ["5 years", "10 years", "100 years", "1000 years"], a: 1, expl: "A decade consists of 10 years." },
        { q: "How many years are there in a century?", opts: ["10 years", "100 years", "1000 years", "50 years"], a: 1, expl: "A century consists of 100 years." },
        { q: "What is the product of 12 x 12?", opts: ["124", "144", "122", "142"], a: 1, expl: "12 times 12 equals 144 (also known as a gross)." },
        { q: "What is the answer when you divide 24 by 8?", opts: ["2", "3", "4", "5"], a: 1, expl: "8 goes into 24 exactly 3 times (8 × 3 = 24)." },
        { q: "The term 'Product' refers to the result of which operation?", opts: ["Addition", "Subtraction", "Multiplication", "Division"], a: 2, expl: "The product is the answer to a multiplication problem." },
        { q: "The term 'Quotient' refers to the result of which operation?", opts: ["Addition", "Subtraction", "Multiplication", "Division"], a: 3, expl: "The quotient is the answer to a division problem." },
        { q: "What is the smallest two-digit whole number?", opts: ["10", "11", "99", "01"], a: 0, expl: "10 is the first number with two digits (1-9 are single digits)." },
        { q: "What is the largest two-digit whole number?", opts: ["90", "99", "100", "19"], a: 1, expl: "99 is the last number before 100 (which has three digits)." },
        { q: "What is the approximate value of Pi (π)?", opts: ["3.14", "3.15", "3.12", "3.16"], a: 0, expl: "Pi is approximately 3.14159..." },
        { q: "How many degrees are in a Right Angle?", opts: ["90 degrees", "180 degrees", "45 degrees", "360 degrees"], a: 0, expl: "A right angle is exactly 90 degrees (like the corner of a square)." },
        { q: "Calculate the average of the numbers: 2, 4, and 6.", opts: ["The average is 2", "The average is 4", "The average is 6", "The average is 12"], a: 1, expl: "Add sum (2+4+6=12), then divide by the count (3). 12 divided by 3 is 4." },
        { q: "What number does the Roman Numeral 'V' represent?", opts: ["1", "5", "10", "50"], a: 1, expl: "V represents the number 5." },
        { q: "What number does the Roman Numeral 'X' represent?", opts: ["5", "10", "50", "100"], a: 1, expl: "X represents the number 10." }
    ],
    "Science": [
        { q: "Which organ is responsible for pumping blood throughout the body?", opts: ["Lungs", "Heart", "Brain", "Liver"], a: 1, expl: "The heart functions as a pump to circulate blood." },
        { q: "What type of symbiotic relationship benefits both organisms involved?", opts: ["Mutualism", "Parasitism", "Commensalism", "Predation"], a: 0, expl: "Mutualism is a relationship where both species benefit from the interaction." },
        { q: "What movement of the Earth causes the cycle of day and night?", opts: ["Rotation", "Revolution", "Tilt", "Orbit"], a: 0, expl: "The Earth's rotation on its axis causes day and night." },
        { q: "Which term describes an animal that possesses a backbone?", opts: ["Vertebrate", "Invertebrate", "Insect", "Worm"], a: 0, expl: "Vertebrates are animals that have a spinal column or backbone." },
        { q: "What is the process by which plants make their own food using sunlight?", opts: ["Photosynthesis", "Respiration", "Digestion", "Absorption"], a: 0, expl: "Photosynthesis is the process used by plants to convert light energy into food." },
        { q: "Which of the following living things requires sunlight to produce food?", opts: ["Rock", "Plant", "Car", "Toy"], a: 1, expl: "Plants are producers that need sunlight for photosynthesis." },
        { q: "Which organ acts as the control center of the human body?", opts: ["Heart", "Brain", "Stomach", "Skin"], a: 1, expl: "The brain controls thoughts, memory, motor skills, and essentially every process in the body." },
        { q: "Which method uses filter paper to separate a solid from a liquid?", opts: ["Filtration", "Decantation", "Sieving", "Evaporation"], a: 0, expl: "Filtration passes a mixture through a barrier (filter paper) to separate solids from fluids." },
        { q: "Which of the following is an example of a homogeneous mixture (solution)?", opts: ["Salt water", "Pizza", "Salad", "Sand water"], a: 0, expl: "Salt water is a homogeneous mixture because the salt is evenly distributed within the water." },
        { q: "What is the process called when a liquid turns into a gas?", opts: ["Evaporation", "Condensation", "Freezing", "Melting"], a: 0, expl: "Evaporation is the process of a liquid changing into a gas or vapor." },
        { q: "What is the solid, outer layer of the Earth called?", opts: ["Crust", "Mantle", "Core", "Atmosphere"], a: 0, expl: "The crust is the outermost solid shell of Earth." },
        { q: "What force pulls objects towards the center of the Earth?", opts: ["Gravity", "Magnetism", "Friction", "Push"], a: 0, expl: "Gravity is the force that attracts two bodies toward each other." },
        { q: "Which of the following is an example of a simple machine?", opts: ["Pulley", "Robot", "iPad", "Bus"], a: 0, expl: "A pulley is a simple machine consisting of a wheel with a grooved rim." },
        { q: "Which planet in our solar system is known as the 'Red Planet'?", opts: ["Mars", "Venus", "Jupiter", "Saturn"], a: 0, expl: "Mars appears red due to iron oxide (rust) on its surface." },
        { q: "What type of change involves a change in form or state but not in chemical composition?", opts: ["Physical Change", "Chemical Change", "Nuclear Change", "Biological Change"], a: 0, expl: "A physical change affects the form of a chemical substance, but not its chemical composition." },
        { q: "Which body system is responsible for breathing and gas exchange?", opts: ["Respiratory System", "Circulatory System", "Digestive System", "Nervous System"], a: 0, expl: "The respiratory system acts to allow gas exchange (oxygen in, carbon dioxide out)." },
        { q: "Which material is a good conductor of heat?", opts: ["Metal", "Wood", "Plastic", "Cloth"], a: 0, expl: "Metals are typically good thermal conductors." },
        { q: "What is considered the basic unit of life?", opts: ["Cell", "Atom", "Molecule", "Organ"], a: 0, expl: "The cell is the smallest structural and functional unit of an organism." },
        { q: "What does the force of friction do to a moving object?", opts: ["Stops motion", "Speeds up", "Cools down", "Lubricates"], a: 0, expl: "Friction is a force that resists relative motion between surfaces." },
        { q: "What gas do humans and animals primarily breathe in for survival?", opts: ["Oxygen", "Carbon Dioxide", "Helium", "Nitrogen"], a: 0, expl: "Oxygen is essential for respiration in most living organisms." },
        { q: "What gas do humans and animals primarily breathe out as waste?", opts: ["Oxygen", "Carbon Dioxide", "Gold", "Iron"], a: 1, expl: "Carbon dioxide is produced as a waste product of metabolism." },
        { q: "Which planet is closest to the Sun?", opts: ["Mercury", "Venus", "Earth", "Mars"], a: 0, expl: "Mercury is the smallest and innermost planet in the Solar System." },
        { q: "Which is the largest planet in our solar system?", opts: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: 0, expl: "Jupiter is a gas giant and the largest planet in our solar system." },
        { q: "Which planet is the hottest in our solar system due to its thick atmosphere?", opts: ["Venus", "Mercury", "Mars", "Earth"], a: 0, expl: "Venus has a thick atmosphere that traps heat, creating a runaway greenhouse effect." },
        { q: "In the water cycle, what is the process where water falls from clouds as rain or snow?", opts: ["Precipitation", "Evaporation", "Condensation", "Collection"], a: 0, expl: "Precipitation is any product of the condensation of atmospheric water vapor that falls under gravity." },
        { q: "What process turns water vapor into liquid water droplets to form clouds?", opts: ["Condensation", "Evaporation", "Precipitation", "Melting"], a: 0, expl: "Condensation is the change of the physical state of matter from gas phase into liquid phase." },
        { q: "What are the three main states of matter?", opts: ["Solid, Liquid, Gas", "Hard, Soft, Wet", "Ice, Water, Steam", "Hot, Cold, Warm"], a: 0, expl: "The fundamental states of matter are solid, liquid, and gas." },
        { q: "What does a herbivore primarily eat?", opts: ["Plants", "Meat", "Both Plants and Meat", "Insects"], a: 0, expl: "Herbivores are animals that feed on plants." },
        { q: "What does a carnivore primarily eat?", opts: ["Meat", "Plants", "Both Plants and Meat", "Dirt"], a: 0, expl: "Carnivores are animals that kill and eat other animals." },
        { q: "What does an omnivore eat?", opts: ["Both Plants and Meat", "Only Meat", "Only Plants", "Nothing"], a: 0, expl: "Omnivores eat both plant and animal matter." },
        { q: "What force opposes the motion of an object sliding on a surface?", opts: ["Friction", "Gravity", "Speed", "Energy"], a: 0, expl: "Friction is the resistance that one surface or object encounters when moving over another." },
        { q: "Which of the following is a natural source of light?", opts: ["Sun", "Moon", "Mirror", "Rock"], a: 0, expl: "The Sun generates its own light through nuclear fusion." },
        { q: "Through which medium does sound travel the fastest?", opts: ["Solid", "Liquid", "Gas", "Vacuum"], a: 0, expl: "Sound travels fastest through solids because particles are packed vertically close together." },
        { q: "What does sound require in order to travel?", opts: ["Medium (like air or water)", "Nothing", "Vacuum", "Silence"], a: 0, expl: "Sound is a mechanical wave that needs a medium to propagate." },
        { q: "What does the term 'opaque' mean when referring to a material?", opts: ["No light passes through", "All light passes through", "Some light passes through", "Clear"], a: 0, expl: "An opaque object is neither transparent (allowing all light) nor translucent (allowing some light)." },
        { q: "What does the term 'transparent' mean?", opts: ["Clear (light passes through)", "Blurry", "Dark", "Blocked"], a: 0, expl: "Transparent materials allow light to pass through so objects behind can be distinctly seen." },
        { q: "What is a primary function of the skeletal system?", opts: ["Support and Protection", "Digestion", "Thinking", "Pumping Blood"], a: 0, expl: "The skeleton provides the structural framework for the body and protects internal organs." },
        { q: "What is a primary function of the skin?", opts: ["Protection as a barrier", "Thinking", "Pumping Blood", "Digesting Food"], a: 0, expl: "The skin protects the body from external elements." },
        { q: "Where does the process of digestion primarily start?", opts: ["Mouth", "Stomach", "Intestine", "Throat"], a: 0, expl: "Digestion begins in the mouth with chewing and saliva." },
        { q: "Which sense organ is responsible for the sense of smell?", opts: ["Nose", "Eyes", "Ears", "Tongue"], a: 0, expl: "The nose contains olfactory receptors for smell." },
        { q: "Which sense organ is responsible for the sense of sight?", opts: ["Eyes", "Nose", "Ears", "Skin"], a: 0, expl: "The eyes detect light and convert it into electro-chemical impulses in neurons." },
        { q: "Which sense organ is responsible for the sense of hearing?", opts: ["Ears", "Eyes", "Nose", "Mouth"], a: 0, expl: "The ear is the organ of hearing and balance." },
        { q: "Which sense organ is responsible for the sense of taste?", opts: ["Tongue", "Teeth", "Lips", "Throat"], a: 0, expl: "The tongue is covered with taste buds." },
        { q: "Which sense organ is responsible for the sense of touch?", opts: ["Skin", "Hair", "Nails", "Bone"], a: 0, expl: "The skin has many nerve endings that react to touch, pressure, heat, and cold." },
        { q: "What is the main function of a plant's roots?", opts: ["Absorb water and nutrients", "Make food", "Attract bees", "Look nice"], a: 0, expl: "Roots anchor the plant and absorb water/nutrients from the soil." },
        { q: "What is the main function of a plant's leaves?", opts: ["Make food (Photosynthesis)", "Absorb water", "Support the plant", "Anchor the plant"], a: 0, expl: "Leaves are the primary site of photosynthesis." },
        { q: "What is the main function of a flower on a plant?", opts: ["Reproduction", "Support", "Growth", "Anchoring"], a: 0, expl: "Flowers are the reproductive structure of flowering plants." },
        { q: "Which of the following is an example of a decomposer?", opts: ["Fungi", "Lion", "Grass", "Bird"], a: 0, expl: "Fungi break down dead or decaying organisms." },
        { q: "Which of the following is an example of a producer in a food chain?", opts: ["Grass", "Cow", "Human", "Eagle"], a: 0, expl: "Grass produces its own food via photosynthesis." },
        { q: "Which of the following is an example of a consumer?", opts: ["Cow", "Grass", "Tree", "Flower"], a: 0, expl: "A cow must eat plants (producers) to get energy." }
    ],
    "English": [
        { q: "Choose the correct word to complete this sentence: 'The ___ students worked hard on their project.'", opts: ["diligent (hardworking)", "diligently (in a hardworking manner)", "diligence (the quality of being hardworking)", "digested (broken down)"], a: 0, expl: "We need an adjective to describe the noun 'students'. 'Diligent' is the correct adjective form." },
        { q: "What is the correct past tense form of the verb 'catch'?", opts: ["Caught", "Catched", "Cot", "Catching"], a: 0, expl: "'Catch' is an irregular verb. Its past tense form is 'caught', not 'catched'." },
        { q: "Which conjunction best completes this sentence: 'I want to go ___ it rained.'", opts: ["but (showing contrast)", "and (adding information)", "so (showing result)", "or (showing choice)"], a: 0, expl: "'But' shows contrast between wanting to go and the fact that it rained." },
        { q: "Which word is a synonym for 'Essential'?", opts: ["Necessary (required)", "Optional (not required)", "Bad (not good)", "Small (little)"], a: 0, expl: "A synonym is a word with the same or similar meaning. Essential and necessary both mean 'required'." },
        { q: "What is the correct plural form of the word 'child'?", opts: ["Children", "Childs", "Kid", "Childes"], a: 0, expl: "'Child' is an irregular noun. Its plural form is 'children', not 'childs'." },
        { q: "Which word is an antonym for 'Brave'?", opts: ["Cowardly (fearful)", "Strong (powerful)", "Fast (quick)", "Hero (brave person)"], a: 0, expl: "An antonym is a word with the opposite meaning. The opposite of brave is cowardly." },
        { q: "Which of the following is an example of a compound sentence?", opts: ["I run, and he walks.", "I run.", "Running is fun.", "Go."], a: 0, expl: "A compound sentence contains two independent clauses joined by a conjunction (and, but, or). 'I run' and 'he walks' are two complete thoughts joined by 'and'." },
        { q: "Which of the following is a reflexive pronoun?", opts: ["Herself", "She", "Her", "Hers"], a: 0, expl: "Reflexive pronouns end in '-self' or '-selves' (myself, yourself, herself, themselves, etc.)." },
        { q: "Complete the sentence with the correct verb form: 'She ___ to school yesterday.'", opts: ["went (past tense)", "go (present)", "goes (present, third person)", "gone (past participle)"], a: 0, expl: "'Yesterday' indicates past tense. The simple past tense of 'go' is 'went'." },
        { q: "What is the comparative form of the adjective 'good'?", opts: ["Better", "Gooder", "Best", "Well"], a: 0, expl: "'Good' is an irregular adjective. Its comparative form is 'better' (not 'gooder'). 'Best' is the superlative form." },
        { q: "The phrase 'Time is money' is an example of which figure of speech?", opts: ["Metaphor (direct comparison)", "Simile (comparison using 'like' or 'as')", "Literal (actual meaning)", "Joke (humorous)"], a: 0, expl: "A metaphor directly compares two unlike things without using 'like' or 'as'. Time is being compared to money." },
        { q: "What does the prefix 'un-' mean?", opts: ["Not (negative)", "Against", "Before", "Two"], a: 0, expl: "The prefix 'un-' means 'not'. For example, 'unhappy' means 'not happy'." },
        { q: "Which is the correct spelling of this word?", opts: ["Receive", "Recieve", "Receve", "Riceive"], a: 0, expl: "The rule is 'I before E except after C'. Since this word has C before the vowel pair, it's spelled 'receive'." },
        { q: "Which of the following words is an adverb?", opts: ["Quickly (describes how)", "Quick (describes what kind)", "Fast (can be adjective or adverb)", "Run (verb)"], a: 0, expl: "Adverbs often end in '-ly' and describe how an action is performed. 'Quickly' describes how something is done." },
        { q: "What does the idiom 'Break a leg' mean?", opts: ["Good luck (encouragement)", "Get hurt (literal injury)", "Fall down", "Run away"], a: 0, expl: "'Break a leg' is an idiom commonly used in theater meaning 'good luck'. It's not meant literally." },
        { q: "Which of the following is an example of an abstract noun?", opts: ["Love (feeling/emotion)", "Table (physical object)", "Dog (living thing)", "City (place)"], a: 0, expl: "Abstract nouns name ideas, emotions, or qualities that cannot be touched. Love is a feeling, not a physical thing." },
        { q: "Which phrase shows the future tense?", opts: ["Will eat", "Ate", "Eats", "Eating"], a: 0, expl: "Future tense uses 'will' + base form of the verb to indicate actions that haven't happened yet." },
        { q: "Which of the following words is an adjective?", opts: ["Blue (describes color)", "Run (action)", "Boy (person)", "Fastly (not a real word)"], a: 0, expl: "Adjectives describe nouns. 'Blue' describes the color of something." },
        { q: "What is a homophone for the word 'sun'?", opts: ["Son (male child)", "San", "Sin", "Sen"], a: 0, expl: "Homophones are words that sound the same but have different meanings and spellings. 'Sun' and 'son' sound identical." },
        { q: "In a story, what is the 'theme'?", opts: ["Lesson or main idea", "Place where it happens", "Action or events", "People in the story"], a: 0, expl: "The theme is the central message, lesson, or main idea of a story." },
        { q: "Which word is typically used in a simile?", opts: ["Like (or 'as')", "Is", "Are", "Was"], a: 0, expl: "Similes use 'like' or 'as' to compare two things. Example: 'She is as brave as a lion' or 'He runs like the wind'." },
        { q: "Which sentence is an example of personification?", opts: ["The wind whispered through the trees.", "The wind blew strongly.", "The wind stopped.", "The wind was fast."], a: 0, expl: "Personification gives human qualities to non-human things. Wind cannot actually whisper, but this gives it a human quality." },
        { q: "Which sentence is an example of hyperbole?", opts: ["I could eat a horse! (exaggeration)", "I am hungry.", "I ate lunch.", "Food is good."], a: 0, expl: "Hyperbole is extreme exaggeration for emphasis. You can't actually eat an entire horse, but this emphasizes how hungry you are." },
        { q: "Which of the following is a proper noun?", opts: ["Manila (specific place)", "city (general place)", "boy (general person)", "dog (general animal)"], a: 0, expl: "Proper nouns name specific people, places, or things and are always capitalized. Manila is a specific city." },
        { q: "Which of the following is a common noun?", opts: ["city (general place)", "Manila (specific place)", "Keisha (specific person)", "Oreo (specific brand)"], a: 0, expl: "Common nouns name general people, places, things, or ideas and are not capitalized (unless at the start of a sentence)." },
        { q: "Which of the following is an example of a collective noun?", opts: ["Team (group of players)", "Player (individual)", "Ball (object)", "Game (event)"], a: 0, expl: "Collective nouns refer to a group of people or things as a single unit. A team is a group of players." },
        { q: "What type of sentence asks a question?", opts: ["Interrogative (ends with ?)", "Statement (ends with .)", "Exclamatory (ends with !)", "Imperative (command)"], a: 0, expl: "Interrogative sentences ask questions and end with a question mark (?)." },
        { q: "What type of sentence gives a command or instruction?", opts: ["Imperative (command)", "Interrogative (question)", "Declarative (statement)", "Exclamatory (emotion)"], a: 0, expl: "Imperative sentences give commands or instructions. Example: 'Sit down.' or 'Clean your room'." },
        { q: "What type of sentence makes a statement?", opts: ["Declarative (statement)", "Interrogative (question)", "Imperative (command)", "Exclamatory (emotion)"], a: 0, expl: "Declarative sentences make statements and end with a period (.)." },
        { q: "What type of sentence shows strong emotion?", opts: ["Exclamatory (shows emotion!)", "Interrogative (asks)", "Imperative (commands)", "Declarative (states)"], a: 0, expl: "Exclamatory sentences express strong emotion and end with an exclamation point (!)." },
        { q: "Which sentence demonstrates correct subject-verb agreement?", opts: ["He runs (singular subject with singular verb)", "He run", "They runs", "We runs"], a: 0, expl: "A singular subject (he) requires a singular verb form (runs). Plural subjects (they, we) use the base form (run)." },
        { q: "What is the irregular plural form of 'mouse'?", opts: ["Mice", "Mouses", "Mouse", "Meeses"], a: 0, expl: "'Mouse' is an irregular noun. Its plural form is 'mice', not 'mouses'." },
        { q: "What is the irregular plural form of 'tooth'?", opts: ["Teeth", "Tooths", "Teethes", "Tooth"], a: 0, expl: "'Tooth' is an irregular noun. Its plural form is 'teeth', not 'tooths'." },
        { q: "What is the simple past tense of the verb 'go'?", opts: ["Went (past tense)", "Goed", "Gone (past participle)", "Going (present participle)"], a: 0, expl: "'Go' is an irregular verb. Its past tense is 'went'. 'Gone' is used with helping verbs (has gone, had gone)." },
        { q: "What is the simple past tense of the verb 'see'?", opts: ["Saw (past tense)", "Seed", "Seen (past participle)", "Seeing (present participle)"], a: 0, expl: "'See' is an irregular verb. Its past tense is 'saw'. 'Seen' is used with helping verbs (has seen, had seen)." },
        { q: "What verb form shows an action happening right now?", opts: ["Running (present progressive with -ing)", "Run (base form)", "Runs (simple present)", "Ran (past)"], a: 0, expl: "Present progressive (also called present continuous) uses 'am/is/are' + verb+ing to show ongoing action." },
        { q: "Which word is a synonym for 'Big'?", opts: ["Large (same meaning)", "Small (opposite)", "Tiny (opposite)", "Little (opposite)"], a: 0, expl: "Synonyms are words with similar meanings. Both 'big' and 'large' mean the same thing." },
        { q: "Which word is an antonym for 'Hot'?", opts: ["Cold (opposite)", "Warm (similar)", "Boiling (more intense)", "Spicy (different meaning)"], a: 0, expl: "Antonyms are words with opposite meanings. Cold is the opposite of hot." },
        { q: "What does the prefix 'pre-' mean?", opts: ["Before", "After", "Not", "Again"], a: 0, expl: "The prefix 'pre-' means 'before'. For example, 'preview' means to view before." },
        { q: "What does the suffix '-ful' mean?", opts: ["Full of", "Empty", "Without", "Action"], a: 0, expl: "The suffix '-ful' means 'full of'. For example, 'beautiful' means 'full of beauty'." },
        { q: "What does the suffix '-less' mean?", opts: ["Without", "With", "More", "Full"], a: 0, expl: "The suffix '-less' means 'without'. For example, 'fearless' means 'without fear'." },
        { q: "What is the root word in 'Acting'?", opts: ["Act (base word)", "Tin", "Ing (suffix)", "Action (related word)"], a: 0, expl: "The root word is the base word before any prefixes or suffixes are added. In 'acting', the root is 'act'." },
        { q: "Which of the following statements is a fact?", opts: ["Ice is cold. (can be proven)", "Ice is bad. (opinion)", "Ice is nice. (opinion)", "I hate ice. (personal feeling)"], a: 0, expl: "A fact is a statement that can be proven true. Ice being cold is measurable and provable." },
        { q: "Which of the following statements is an opinion?", opts: ["Blue is the best color. (personal belief)", "The sky is blue. (fact)", "Grass is green. (fact)", "Water is wet. (fact)"], a: 0, expl: "An opinion is a personal belief or judgment that cannot be proven. What is 'best' varies from person to person." },
        { q: "In a cause-and-effect relationship, what is the 'cause'?", opts: ["Reason (why it happened)", "Result (what happened)", "Effect (outcome)", "End (conclusion)"], a: 0, expl: "The cause is the reason something happened. It's what made the effect occur." },
        { q: "In a cause-and-effect relationship, what is the 'effect'?", opts: ["Result (what happened)", "Reason (why)", "Cause (trigger)", "Start (beginning)"], a: 0, expl: "The effect is the result or outcome. It's what happened because of the cause." },
        { q: "In writing, what is 'first person' point of view?", opts: ["I/We (the speaker)", "He/She (someone else)", "You (the listener)", "They (others)"], a: 0, expl: "First person uses 'I' or 'we'. The narrator is part of the story." },
        { q: "In writing, what is 'second person' point of view?", opts: ["You (the listener/reader)", "I (the speaker)", "He (someone else)", "We (group including speaker)"], a: 0, expl: "Second person uses 'you'. The narrator speaks directly to the reader." },
        { q: "In writing, what is 'third person' point of view?", opts: ["He/She/It (someone else)", "I (speaker)", "You (reader)", "We (group)"], a: 0, expl: "Third person uses 'he', 'she', 'it', or 'they'. The narrator is an outside observer." }
    ],
    "Filipino": [
        { q: "Pandiwa?", opts: ["Takbo", "Bato", "Pula", "Ako"], a: 0, expl: "Kilos." },
        { q: "Kasingkahulugan: Marikit?", opts: ["Maganda", "Pangit", "Mabaho", "Luma"], a: 0, expl: "Beautiful." },
        { q: "Ama ng Wika?", opts: ["Quezon", "Rizal", "Bonifacio", "Mabini"], a: 0, expl: "Manuel L. Quezon." },
        { q: "Salitang ugat: Lumakad?", opts: ["Lakad", "Lum", "Akad", "La"], a: 0, expl: "Base word." },
        { q: "Gamit ng 'ng'?", opts: ["Pang-ukol", "Pantukoy", "Pangatnig", "Pang-abay"], a: 0, expl: "Object marker." },
        { q: "Kasalungat: Masipag?", opts: ["Tamad", "Mabilis", "Mabait", "Mahusay"], a: 0, expl: "Lazy." },
        { q: "Pang-uri?", opts: ["Matalino", "Bata", "Aaral", "Kami"], a: 0, expl: "Describing." },
        { q: "Patanong?", opts: ["Saan ka pupunta?", "Ayaw ko.", "Dito lang.", "Wow!"], a: 0, expl: "Question." },
        { q: "Panghalip Panao?", opts: ["Ako", "Ito", "Doon", "Sino"], a: 0, expl: "Personal Pronoun." },
        { q: "Baybay?", opts: ["Himpapawid", "Himpapawir", "Himpapawids", "Himpawid"], a: 0, expl: "Spelling." },
        { q: "Hiram?", opts: ["Keyk", "Tinapay", "Lapis", "Papel"], a: 0, expl: "Cake." },
        { q: "Simuno?", opts: ["Pinag-uusapan", "Kilos", "Katangian", "Lugar"], a: 0, expl: "Subject." },
        { q: "Tambalang salita?", opts: ["Bahaghari", "Bahay", "Araw", "Ulan"], a: 0, expl: "Compound." },
        { q: "Pagmamalabis?", opts: ["Bumaha ng luha", "Umiyak siya", "Mataas ang tubig", " basa ang lupa"], a: 0, expl: "Hyperbole." },
        { q: "Pasukdol?", opts: ["Pinakamabait", "Mas mabait", "Mabait", "Di mabait"], a: 0, expl: "Superlative." },
        { q: "Salitang kilos?", opts: ["Sayaw", "Ganda", "Saya", "Araw"], a: 0, expl: "Verb." },
        { q: "Panandang 'Ang'?", opts: ["Pantukoy", "Pangatnig", "Pang-ukol", "Pang-abay"], a: 0, expl: "Focus marker." },
        { q: "Patinig?", opts: ["A, E, I, O, U", "B, K, D", "L, M, N", "W, Y"], a: 0, expl: "Vowels." },
        { q: "Katinig?", opts: ["B, K, D...", "A, E, I...", "1, 2, 3", "Lahat"], a: 0, expl: "Consonants." },
        { q: "Paksa?", opts: ["Pinag-uusapan", "Kilos", "Dulo", "Pamagat"], a: 0, expl: "Topic." },
        { q: "Gitling?", opts: ["Araw-araw", "Arawaraw", "Ara waraw", "Ara-waraw"], a: 0, expl: "Hyphen." },
        { q: "Pangngalang Pambalana?", opts: ["bansa", "Pilipinas", "Japan", "USA"], a: 0, expl: "Common noun." },
        { q: "Pangngalang Pantangi?", opts: ["Luneta", "parke", "pasyalan", "lugar"], a: 0, expl: "Proper noun." },
        { q: "Kasarian: Panlalaki?", opts: ["Kuya", "Ate", "Nanay", "Guro"], a: 0, expl: "Male." },
        { q: "Kasarian: Pambabae?", opts: ["Lola", "Lolo", "Tatay", "Pulis"], a: 0, expl: "Female." },
        { q: "Kasarian: Di-tiyak?", opts: ["Pulis", "Nanay", "Tatay", "Kuya"], a: 0, expl: "Unsure gender." },
        { q: "Kasarian: Walang Kasarian?", opts: ["Lapis", "Nanay", "Tatay", "Aso"], a: 0, expl: "Object." },
        { q: "Kailanan: Isahan?", opts: ["Ako", "Kami", "Tayo", "Sila"], a: 0, expl: "Singular." },
        { q: "Kailanan: Maramihan?", opts: ["Sila", "Siya", "Ikaw", "Niya"], a: 0, expl: "Plural." },
        { q: "Pangatnig?", opts: ["At", "Ay", "Ang", "Si"], a: 0, expl: "Conjunction." },
        { q: "Pang-ukol?", opts: ["Para kay", "At", "O", "Dahil"], a: 0, expl: "Preposition." },
        { q: "Pang-abay?", opts: ["Mabilis tumakbo", "Mabilis kotse", "Mabilis ito", "Siya ay mabilis"], a: 0, expl: "Modifies verb." },
        { q: "Magkasingkahulugan?", opts: ["Tuwa-Saya", "Tuwa-Lungkot", "Taas-Baba", "Init-Lamig"], a: 0, expl: "Synonyms." },
        { q: "Magkasalungat?", opts: ["Taas-Baba", "Tuwa-Saya", "Ganda-Rikit", "Linis-Ayos"], a: 0, expl: "Antonyms." },
        { q: "Sanhi?", opts: ["Dahilan", "Bunga", "Kinalabasan", "Wakas"], a: 0, expl: "Cause." },
        { q: "Bunga?", opts: ["Resulta", "Dahilan", "Simula", "Pinagmulan"], a: 0, expl: "Effect." },
        { q: "Tugma?", opts: ["Bata-Mata", "Bata-Lapis", "Bata-Aso", "Bata-Langit"], a: 0, expl: "Rhyme." },
        { q: "Pabula?", opts: ["Hayop ang tauhan", "Tao", "Dwende", "Diyos"], a: 0, expl: "Fable." },
        { q: "Alamat?", opts: ["Pinagmulan", "Balita", "Kasaysayan", "Tula"], a: 0, expl: "Legend." },
        { q: "Kwentong Bayan?", opts: ["Folktale", "News", "Science", "Math"], a: 0, expl: "Culture story." },
        { q: "Bugtong?", opts: ["Palaisipan", "Kwento", "Tula", "Awit"], a: 0, expl: "Riddle." },
        { q: "Salawikain?", opts: ["Aral", "Biro", "Sabi", "Sigaw"], a: 0, expl: "Proverb." },
        { q: "Banghay?", opts: ["Pangyayari", "Tauhan", "Lugar", "Aral"], a: 0, expl: "Plot." },
        { q: "Tagpuan?", opts: ["Lugar/Oras", "Tao", "Kilos", "Resulta"], a: 0, expl: "Setting." },
        { q: "Tauhan?", opts: ["Gumaganap", "Lugar", "Aral", "Banghay"], a: 0, expl: "Character." },
        { q: "Wakas?", opts: ["Katapusan", "Simula", "Gitna", "Dahilan"], a: 0, expl: "Ending." },
        { q: "Pamagat?", opts: ["Titulo", "Wakas", "Aral", "Tauhan"], a: 0, expl: "Title." },
        { q: "Gitna?", opts: ["Kasukdulan", "Simula", "Wakas", "Pamagat"], a: 0, expl: "Middle." }
    ],
    "Araling Panlipunan": [
        { q: "KKK founder?", opts: ["Bonifacio", "Rizal", "Mabini", "Aguinaldo"], a: 0, expl: "Andres Bonifacio." },
        { q: "Independence Day?", opts: ["June 12", "July 4", "May 1", "Aug 30"], a: 0, expl: "1898 from Spain." },
        { q: "Gov Type?", opts: ["Democratic", "Monarchy", "Communist", "Dictator"], a: 0, expl: "Republic." },
        { q: "National Hero?", opts: ["Rizal", "Bonifacio", "Luna", "Lapu-Lapu"], a: 0, expl: "Jose Rizal." },
        { q: "First President?", opts: ["Aguinaldo", "Quezon", "Roxas", "Marcos"], a: 0, expl: "Emilio Aguinaldo." },
        { q: "Utak ng Katipunan?", opts: ["Jacinto", "Mabini", "Bonifacio", "Luna"], a: 0, expl: "Emilio Jacinto." },
        { q: "Dakilang Lumpo?", opts: ["Mabini", "Jacinto", "Rizal", "Aguinaldo"], a: 0, expl: "Paralytic advisor." },
        { q: "Martial Law declared?", opts: ["1972", "1986", "1990", "2000"], a: 0, expl: "Marcos era." },
        { q: "Cry of Pugad Lawin?", opts: ["Quezon City", "Cavite", "Laguna", "Manila"], a: 0, expl: "Tearing cedulas." },
        { q: "Ousted Marcos?", opts: ["EDSA 1", "EDSA 2", "EDSA 3", "War"], a: 0, expl: "People Power 1986." },
        { q: "3 Stars mean?", opts: ["Luzon Visayas Mindanao", "Faith Hope Love", "3 Heroes", "3 Wars"], a: 0, expl: "Island groups." },
        { q: "Sun rays?", opts: ["8 Provinces", "8 Heroes", "8 Days", "8 Islands"], a: 0, expl: "Reavolting provinces." },
        { q: "National Bird?", opts: ["Eagle", "Maya", "Parrot", "Owl"], a: 0, expl: "Phil Eagle." },
        { q: "Highest Peak?", opts: ["Apo", "Mayon", "Taal", "Pinatubo"], a: 0, expl: "Davao." },
        { q: "Salad Bowl?", opts: ["Benguet", "Davao", "Baguio", "Manila"], a: 0, expl: "Vegetables." },
        { q: "National Flower?", opts: ["Sampaguita", "Rose", "Daisy", "Lily"], a: 0, expl: "White flower." },
        { q: "Defeated Magellan?", opts: ["Lapu-Lapu", "Sikatuna", "Humabon", "Rizal"], a: 0, expl: "Battle of Mactan." },
        { q: "Independence 1946?", opts: ["USA", "Spain", "Japan", "China"], a: 0, expl: "July 4 from USA." },
        { q: "3 Branches?", opts: ["Exec, Legis, Judi", "Pres, VP, Sen", "May, Gov, Cap", "Pol, Mil, Civ"], a: 0, expl: "Separation of powers." },
        { q: "Constitution year?", opts: ["1987", "1972", "1935", "1898"], a: 0, expl: "Current one." },
        { q: "Discoverer of Ph?", opts: ["Magellan", "Columbus", "Cook", "Marcos"], a: 0, expl: "For Spain in 1521." },
        { q: "Longest Bridge?", opts: ["San Juanico", "Mactan", "Jones", "Ayala"], a: 0, expl: "Samar-Leyte." },
        { q: "Summer Capital?", opts: ["Baguio", "Manila", "Tagaytay", "Cebu"], a: 0, expl: "Cool climate." },
        { q: "Walled City?", opts: ["Intramuros", "Makati", "BGC", "Vigan"], a: 0, expl: "Old Manila." },
        { q: "Oldest City?", opts: ["Cebu", "Manila", "Davao", "Iloilo"], a: 0, expl: "Queen City." },
        { q: "Shoe Capital?", opts: ["Marikina", "Laguna", "Pampanga", "Rizal"], a: 0, expl: "Shoes." },
        { q: "Textile Capital?", opts: ["Bulacan", "Batangas", "Ilocos", "Laguna"], a: 0, expl: "Often looms." },
        { q: "Sugar Bowl?", opts: ["Negros", "Cebu", "Panay", "Bohol"], a: 0, expl: "Sugar cane." },
        { q: "Pearl of Orient?", opts: ["Philippines", "Japan", "China", "Thailand"], a: 0, expl: "Nickname." },
        { q: "Gateway to Asia?", opts: ["Philippines", "Singapore", "Hong Kong", "Japan"], a: 0, expl: "Strategic loc." },
        { q: "National Sport?", opts: ["Arnis", "Basketball", "Boxing", "Sipa"], a: 0, expl: "Law mandated." },
        { q: "National House?", opts: ["Bahay Kubo", "Mansion", "Condo", "Tent"], a: 0, expl: "Nipa Hut." },
        { q: "Create laws?", opts: ["Legislative", "Executive", "Judicial", "Police"], a: 0, expl: "Congress." },
        { q: "Implement laws?", opts: ["Executive", "Legislative", "Judicial", "Police"], a: 0, expl: "President." },
        { q: "Interpret laws?", opts: ["Judicial", "Executive", "Legislative", "Police"], a: 0, expl: "Supreme Court." },
        { q: "No. of Senators?", opts: ["24", "12", "50", "200"], a: 0, expl: "Senate." },
        { q: "Term of President?", opts: ["6 years", "4 years", "3 years", "10 years"], a: 0, expl: "No reelection." },
        { q: "Minimum voting age?", opts: ["18", "21", "16", "25"], a: 0, expl: "Suffrage." },
        { q: "National Language?", opts: ["Filipino", "English", "Cebuano", "Spanish"], a: 0, expl: "Based on Tagalog." },
        { q: "Capital of Ph?", opts: ["Manila", "Quezon City", "Cebu", "Davao"], a: 0, expl: "Metro Manila." },
        { q: "Barasoain Church loc?", opts: ["Bulacan", "Manila", "Cavite", "Laguna"], a: 0, expl: "Malolos Congress." },
        { q: "Rizal died in?", opts: ["Luneta", "Dapitan", "Calamba", "Spain"], a: 0, expl: "Bagumbayan." },
        { q: "Rizal born in?", opts: ["Calamba", "Manila", "Dapitan", "Europe"], a: 0, expl: "Laguna." },
        { q: "Spoliarium painter?", opts: ["Juan Luna", "Amorsolo", "Botong", "Rizal"], a: 0, expl: "Famous painting." },
        { q: "First hero?", opts: ["Lapu-Lapu", "Rizal", "Bonifacio", "Aguinaldo"], a: 0, expl: "Mactan battle." },
        { q: "Japanese occupation?", opts: ["1942-1945", "1898-1901", "1900-1910", "1972-1981"], a: 0, expl: "WW2." },
        { q: "American period?", opts: ["1898-1946", "1521-1898", "1946-Present", "1900-1920"], a: 0, expl: "After Spain." },
        { q: "Spanish period?", opts: ["333 years", "100 years", "50 years", "500 years"], a: 0, expl: "3 centuries." }
    ]
};
