const db = {
    "Mathematics": [
        { q: "What is the value of N in: 5 + (3 × 4) - 2 = N?", opts: ["15", "10", "17", "20"], a: 0, expl: "PEMDAS: 3×4=12, 5+12=17, 17-2=15." },
        { q: "Which fraction is equivalent to 0.75?", opts: ["1/2", "3/4", "3/5", "7/5"], a: 1, expl: "0.75 is 75/100 = 3/4." },
        { q: "Perimeter of a rectangle with length 10cm and width 5cm?", opts: ["30cm", "50cm", "15cm", "25cm"], a: 0, expl: "P = 2(L+W) = 2(15) = 30." },
        { q: "What is 25% of 200?", opts: ["25", "50", "75", "100"], a: 1, expl: "200 × 0.25 = 50." },
        { q: "Solve: 1/2 + 1/4", opts: ["3/4", "2/4", "1/8", "1/6"], a: 0, expl: "2/4 + 1/4 = 3/4." },
        { q: "Which number is divisible by 3?", opts: ["10", "13", "15", "20"], a: 2, expl: "1+5=6, which is divisible by 3." },
        { q: "GCF of 12 and 18?", opts: ["3", "6", "9", "12"], a: 1, expl: "Factors: 12(1,2,3,4,6,12), 18(1,2,3,6,9,18). GCF is 6." },
        { q: "Convert 3.5 to mixed number.", opts: ["3 1/2", "3 1/5", "3 1/4", "3 3/5"], a: 0, expl: "0.5 = 1/2." },
        { q: "Area of square with side 6cm?", opts: ["24", "12", "36", "30"], a: 2, expl: "Area = 6×6 = 36." },
        { q: "If x=5, what is 2x+3?", opts: ["10", "13", "8", "15"], a: 1, expl: "2(5)+3 = 10+3 = 13." },
        { q: "Integer greater than -5?", opts: ["-10", "-6", "-8", "-1"], a: 3, expl: "-1 is to the right of -5." },
        { q: "Ratio of 4 apples to 8 bananas?", opts: ["2:1", "1:2", "4:8", "1:4"], a: 1, expl: "4:8 = 1:2." },
        { q: "10 - 3.45 = ?", opts: ["6.55", "7.55", "6.65", "7.45"], a: 0, expl: "10.00 - 3.45 = 6.55." },
        { q: "Cm in 2 meters?", opts: ["20", "200", "2000", "0.2"], a: 1, expl: "1m = 100cm." },
        { q: "Volume of cube with edge 3cm?", opts: ["9", "18", "27", "12"], a: 2, expl: "3×3×3 = 27." },
        { q: "Prime number?", opts: ["9", "15", "21", "2"], a: 3, expl: "2 is only even prime." },
        { q: "Round 45,678 to nearest thousand.", opts: ["45,000", "46,000", "50,000", "45,700"], a: 1, expl: "5 rounds up to 6." },
        { q: "15 is what % of 60?", opts: ["25%", "20%", "50%", "10%"], a: 0, expl: "15/60 = 1/4 = 25%." },
        { q: "0.5 x 0.2?", opts: ["1.0", "0.1", "0.01", "0.25"], a: 1, expl: "5x2=10, 2 decimal places -> 0.10." },
        { q: "Sum of triangle angles?", opts: ["90", "180", "360", "100"], a: 1, expl: "Always 180 degrees." },
        { q: "Supplementary angles sum to?", opts: ["90", "180", "360", "45"], a: 1, expl: "Supplementary = 180." },
        { q: "Complementary angles sum to?", opts: ["90", "180", "360", "45"], a: 0, expl: "Complementary = 90." },
        { q: "Centi- means?", opts: ["100", "1/100", "1000", "1/1000"], a: 1, expl: "One hundredth." },
        { q: "Kilo- means?", opts: ["100", "1/100", "1000", "1/1000"], a: 2, expl: "One thousand." },
        { q: "Square root of 81?", opts: ["8", "9", "7", "6"], a: 1, expl: "9x9=81." },
        { q: "3 squared?", opts: ["6", "9", "12", "3"], a: 1, expl: "3x3=9." },
        { q: "Reciprocal of 2/3?", opts: ["3/2", "2/3", "1/3", "4/3"], a: 0, expl: "Flip the fraction." },
        { q: "LCM of 4 and 5?", opts: ["10", "20", "15", "25"], a: 1, expl: "Multiples of 4: 4,8,12,16,20. 5: 5,10,15,20." },
        { q: "Simplest form of 10/20?", opts: ["1/2", "2/4", "5/10", "1/5"], a: 0, expl: "Divide by 10." },
        { q: "Decimal for 1/4?", opts: ["0.5", "0.25", "0.75", "0.4"], a: 1, expl: "1 divided by 4." },
        { q: "20% of 50?", opts: ["10", "20", "5", "15"], a: 0, expl: "0.2 x 50 = 10." },
        { q: "Vertices in a triangle?", opts: ["3", "4", "5", "6"], a: 0, expl: "3 vertices." },
        { q: "Faces in a cube?", opts: ["4", "6", "8", "12"], a: 1, expl: "Top, bottom, 4 sides." },
        { q: "Formula for Area of Circle?", opts: ["2πr", "πr²", "L×W", "½bh"], a: 1, expl: "Pi r squared." },
        { q: "Circumference formula?", opts: ["2πr", "πr²", "bh", "s²"], a: 0, expl: "2 Pi r." },
        { q: "Odd number?", opts: ["2", "4", "7", "10"], a: 2, expl: "Not divisible by 2." },
        { q: "Usually used to measure water?", opts: ["Gram", "Liter", "Meter", "Second"], a: 1, expl: "Volume." },
        { q: "Years in a decade?", opts: ["5", "10", "100", "1000"], a: 1, expl: "Deca = 10." },
        { q: "Years in a century?", opts: ["10", "100", "1000", "50"], a: 1, expl: "Cent = 100." },
        { q: "12 x 12?", opts: ["124", "144", "122", "142"], a: 1, expl: "Gross." },
        { q: "24 divided by 8?", opts: ["2", "3", "4", "5"], a: 1, expl: "8x3=24." },
        { q: "Product means?", opts: ["Add", "Subtract", "Multiply", "Divide"], a: 2, expl: "Result of multiplication." },
        { q: "Quotient means?", opts: ["Add", "Subtract", "Multiply", "Divide"], a: 3, expl: "Result of division." },
        { q: "Smallest 2 digit number?", opts: ["10", "11", "99", "01"], a: 0, expl: "10." },
        { q: "Largest 2 digit number?", opts: ["90", "99", "100", "19"], a: 1, expl: "99." },
        { q: "Value of pi?", opts: ["3.14", "3.15", "3.12", "3.16"], a: 0, expl: "Approx 3.14159." },
        { q: "Right angle degrees?", opts: ["90", "180", "45", "360"], a: 0, expl: "90 degrees." },
        { q: "Average of 2, 4, 6?", opts: ["2", "4", "6", "12"], a: 1, expl: "(2+4+6)/3 = 12/3 = 4." },
        { q: "Roman numeral V?", opts: ["1", "5", "10", "50"], a: 1, expl: "V is 5." },
        { q: "Roman numeral X?", opts: ["5", "10", "50", "100"], a: 1, expl: "X is 10." }
    ],
    "Science": [
        { q: "Pumps blood?", opts: ["Lungs", "Heart", "Brain", "Liver"], a: 1, expl: "The heart pumps blood." },
        { q: "Both benefit?", opts: ["Mutualism", "Parasitism", "Commensalism", "Predation"], a: 0, expl: "Win-win relationship." },
        { q: "Day and night cause?", opts: ["Rotation", "Revolution", "Tilt", "Orbit"], a: 0, expl: "Spinning on axis." },
        { q: "With backbone?", opts: ["Vertebrate", "Invertebrate", "Insect", "Worm"], a: 0, expl: "Spine = Vertebrate." },
        { q: "Plants make food?", opts: ["Photosynthesis", "Respiration", "Digestion", "Absorption"], a: 0, expl: "Using sunlight." },
        { q: "Need sunlight?", opts: ["Rock", "Plant", "Car", "Toy"], a: 1, expl: "Plants need light." },
        { q: "Control center?", opts: ["Heart", "Brain", "Stomach", "Skin"], a: 1, expl: "The brain controls body." },
        { q: "Filter paper used?", opts: ["Filtration", "Decantation", "Sieving", "Evaporation"], a: 0, expl: "Filters solids." },
        { q: "Homogeneous?", opts: ["Salt water", "Pizza", "Salad", "Sand water"], a: 0, expl: "Uniform mixture." },
        { q: "Liquid to Gas?", opts: ["Evaporation", "Condensation", "Freezing", "Melting"], a: 0, expl: "Boiling/Evaporating." },
        { q: "Outer, solid layer?", opts: ["Crust", "Mantle", "Core", "Atmosphere"], a: 0, expl: "Earth's crust." },
        { q: "Pull to Earth?", opts: ["Gravity", "Magnetism", "Friction", "Push"], a: 0, expl: "Gravity." },
        { q: "Simple machine?", opts: ["Pulley", "Robot", "iPad", "Bus"], a: 0, expl: "Basic mechanical device." },
        { q: "Red Planet?", opts: ["Mars", "Venus", "Jupiter", "Saturn"], a: 0, expl: "Iron oxide makes it red." },
        { q: "Change in form only?", opts: ["Physical", "Chemical", "Nuclear", "Biological"], a: 0, expl: "No new substance." },
        { q: "Breathing system?", opts: ["Respiratory", "Circulatory", "Digestive", "Nervous"], a: 0, expl: "Lungs and airways." },
        { q: "Conductor of heat?", opts: ["Metal", "Wood", "Plastic", "Cloth"], a: 0, expl: "Metals conduct well." },
        { q: "Unit of life?", opts: ["Cell", "Atom", "Molecule", "Organ"], a: 0, expl: "Basic building block." },
        { q: "Friction does what?", opts: ["Stops motion", "Speeds up", "Cools", "Lubricates"], a: 0, expl: "Resists motion." },
        { q: "Gas we breathe in?", opts: ["Oxygen", "Carbon Dioxide", "Helium", "Nitrogen"], a: 0, expl: "Needed for life." },
        { q: "Gas we breathe out?", opts: ["Oxygen", "Carbon Dioxide", "Gold", "Iron"], a: 1, expl: "Waste product." },
        { q: "Planet closest to Sun?", opts: ["Mercury", "Venus", "Earth", "Mars"], a: 0, expl: "Mercury is first." },
        { q: "Largest planet?", opts: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: 0, expl: "Jupiter fits many Earths." },
        { q: "Hottest planet?", opts: ["Venus", "Mercury", "Mars", "Earth"], a: 0, expl: "Venus has greenhouse effect." },
        { q: "Water cycle rain?", opts: ["Precipitation", "Evaporation", "Condensation", "Collection"], a: 0, expl: "Falling water." },
        { q: "Cloud formation?", opts: ["Condensation", "Evaporation", "Precipitation", "Melting"], a: 0, expl: "Vapor to liquid." },
        { q: "3 states of matter?", opts: ["Solid Liquid Gas", "Hard Soft Wet", "Ice Water Steam", "Hot Cold Warm"], a: 0, expl: "States." },
        { q: "Herbivore eats?", opts: ["Plants", "Meat", "Both", "Insects"], a: 0, expl: "Herbs = plants." },
        { q: "Carnivore eats?", opts: ["Meat", "Plants", "Both", "Dirt"], a: 0, expl: "Carne = meat." },
        { q: "Omnivore eats?", opts: ["Both", "Meat", "Plants", "None"], a: 0, expl: "Omni = all." },
        { q: "Force that opposes motion?", opts: ["Friction", "Gravity", "Speed", "Energy"], a: 0, expl: "Rubbing surfaces." },
        { q: "Light source?", opts: ["Sun", "Moon", "Mirror", "Rock"], a: 0, expl: "Sun produce light." },
        { q: "Sound travels fast in?", opts: ["Solid", "Liquid", "Gas", "Vacuum"], a: 0, expl: "Molecules are close." },
        { q: "Sound needs?", opts: ["Medium", "Nothing", "Vacuum", "Silence"], a: 0, expl: "Cannot travel in vacuum." },
        { q: "Opaque means?", opts: ["No light passes", "All light passes", "Some light passes", "Clear"], a: 0, expl: "Blocks light." },
        { q: "Transparent means?", opts: ["Clear", "Blurry", "Dark", "Blocked"], a: 0, expl: "See through." },
        { q: "Skeleton function?", opts: ["Support", "Digestion", "Thinking", "Pumping"], a: 0, expl: "Structure." },
        { q: "Skin function?", opts: ["Protection", "Thinking", "Pumping", "Digesting"], a: 0, expl: "Barrier." },
        { q: "Digestive start?", opts: ["Mouth", "Stomach", "Intestine", "Throat"], a: 0, expl: "Chewing." },
        { q: "Sense of smell?", opts: ["Nose", "Eyes", "Ears", "Tongue"], a: 0, expl: "Olfactory." },
        { q: "Sense of sight?", opts: ["Eyes", "Nose", "Ears", "Skin"], a: 0, expl: "Visual." },
        { q: "Sense of hearing?", opts: ["Ears", "Eyes", "Nose", "Mouth"], a: 0, expl: "Auditory." },
        { q: "Sense of taste?", opts: ["Tongue", "Teeth", "Lips", "Throat"], a: 0, expl: "Taste buds." },
        { q: "Sense of touch?", opts: ["Skin", "Hair", "Nails", "Bone"], a: 0, expl: "Nerves in skin." },
        { q: "Root function?", opts: ["Absorb water", "Make food", "Attract bees", "Look nice"], a: 0, expl: "From soil." },
        { q: "Leaf function?", opts: ["Make food", "Absorb water", "Support", "Anchor"], a: 0, expl: "Photosynthesis." },
        { q: "Flower function?", opts: ["Reproduction", "Support", "Growth", "Anchoring"], a: 0, expl: "Seeds." },
        { q: "Decomposer example?", opts: ["Fungi", "Lion", "Grass", "Bird"], a: 0, expl: "Breaks down dead stuff." },
        { q: "Producer example?", opts: ["Grass", "Cow", "Human", "Eagle"], a: 0, expl: "Makes own food." },
        { q: "Consumer example?", opts: ["Cow", "Grass", "Tree", "Flower"], a: 0, expl: "Eats others." }
    ],
    "English": [
        { q: "The ___ students.", opts: ["diligent", "diligently", "diligence", "digested"], a: 0, expl: "Adjective describes students." },
        { q: "Past tense of catch?", opts: ["Caught", "Catched", "Cot", "Catching"], a: 0, expl: "Irregular." },
        { q: "Conjunction: I want to go ___ it rained.", opts: ["but", "and", "so", "or"], a: 0, expl: "Contrast." },
        { q: "Synonym: Essential?", opts: ["Necessary", "Optional", "Bad", "Small"], a: 0, expl: "Need it." },
        { q: "Plural of child?", opts: ["Children", "Childs", "Kid", "Childes"], a: 0, expl: "Irregular." },
        { q: "Antonym: Brave?", opts: ["Cowardly", "Strong", "Fast", "Hero"], a: 0, expl: "Opposite." },
        { q: "Compound sentence?", opts: ["I run, and he walks.", "I run.", "Running is fun.", "Go."], a: 0, expl: "Two clauses join by comma+and." },
        { q: "Reflexive pronoun?", opts: ["Herself", "She", "Her", "Hers"], a: 0, expl: "Self." },
        { q: "She ___ to school yesterday.", opts: ["went", "go", "goes", "gone"], a: 0, expl: "Past tense." },
        { q: "Better than good?", opts: ["Better", "Gooder", "Best", "Well"], a: 0, expl: "Comparative." },
        { q: "Time is money?", opts: ["Metaphor", "Simile", "Literal", "Joke"], a: 0, expl: "Direct comparison." },
        { q: "Prefix 'un-'?", opts: ["Not", "Against", "Before", "Two"], a: 0, expl: "Unhappy = Not happy." },
        { q: "Spelling?", opts: ["Receive", "Recieve", "Receve", "Riceive"], a: 0, expl: "EI after C." },
        { q: "Adverb?", opts: ["Quickly", "Quick", "Fast", "Run"], a: 0, expl: "Ends in ly usually." },
        { q: "Break a leg?", opts: ["Good luck", "Get hurt", "Fall", "Run"], a: 0, expl: "Idiom." },
        { q: "Abstract noun?", opts: ["Love", "Table", "Dog", "City"], a: 0, expl: "Idea/Feeling." },
        { q: "Future tense?", opts: ["Will eat", "Ate", "Eats", "Eating"], a: 0, expl: "Will + verb." },
        { q: "Adjective?", opts: ["Blue", "Run", "Boy", "Fastly"], a: 0, expl: "Describes noun." },
        { q: "Homophone sun?", opts: ["Son", "San", "Sin", "Sen"], a: 0, expl: "Sounds same." },
        { q: "Theme?", opts: ["Lesson", "Place", "Action", "People"], a: 0, expl: "Main idea." },
        { q: "Simile keyword?", opts: ["Like", "Is", "Are", "Was"], a: 0, expl: "Like or as." },
        { q: "Personification?", opts: ["Wind whispered", "Wind blew", "Wind stopped", "Wind fast"], a: 0, expl: "Human qualities." },
        { q: "Hyperbole?", opts: ["I could eat a horse", "I am hungry", "I ate lunch", "Food is good"], a: 0, expl: "Exaggeration." },
        { q: "Proper noun?", opts: ["Manila", "city", "boy", "dog"], a: 0, expl: "Specific name." },
        { q: "Common noun?", opts: ["city", "Manila", "Keisha", "Oreo"], a: 0, expl: "General name." },
        { q: "Collective noun?", opts: ["Team", "Player", "Ball", "Game"], a: 0, expl: "Group." },
        { q: "Interrogative?", opts: ["Question?", "Statement.", "Shout!", "Order."], a: 0, expl: "? mark." },
        { q: "Imperative?", opts: ["Sit down.", "I sit.", "Do I sit?", "Wow!"], a: 0, expl: "Command." },
        { q: "Declarative?", opts: ["I like blue.", "Do you?", "Run!", "Ouch!"], a: 0, expl: "Statement." },
        { q: "Exclamatory?", opts: ["Ouch!", "Ok.", "Why?", "Yes."], a: 0, expl: "Strong emotion." },
        { q: "Subject-Verb Agreement?", opts: ["He runs", "He run", "They runs", "We runs"], a: 0, expl: "Singular subject, s verb." },
        { q: "Plural of mouse?", opts: ["Mice", "Mouses", "Mouse", "Meeses"], a: 0, expl: "Irregular." },
        { q: "Plural of tooth?", opts: ["Teeth", "Tooths", "Teethes", "Tooth"], a: 0, expl: "Irregular." },
        { q: "Past of go?", opts: ["Went", "Goed", "Gone", "Going"], a: 0, expl: "Irregular." },
        { q: "Past of see?", opts: ["Saw", "Seed", "Seen", "Seeing"], a: 0, expl: "Irregular." },
        { q: "Present progressive?", opts: ["Running", "Run", "Runs", "Ran"], a: 0, expl: "-ing." },
        { q: "Synonym: Big?", opts: ["Large", "Small", "Tiny", "Little"], a: 0, expl: "Same meaning." },
        { q: "Antonym: Hot?", opts: ["Cold", "Warm", "Boiling", "Spicy"], a: 0, expl: "Opposite." },
        { q: "Prefix 'pre-'?", opts: ["Before", "After", "Not", "Again"], a: 0, expl: "Preview." },
        { q: "Suffix '-ful'?", opts: ["Full of", "Empty", "Without", "Action"], a: 0, expl: "Beautiful." },
        { q: "Suffix '-less'?", opts: ["Without", "With", "More", "Full"], a: 0, expl: "Fearless." },
        { q: "Root word: Acting?", opts: ["Act", "Tin", "Ing", "Action"], a: 0, expl: "Base." },
        { q: "Fact?", opts: ["Ice is cold.", "Ice is bad.", "Ice is nice.", "I hate ice."], a: 0, expl: "Provable." },
        { q: "Opinion?", opts: ["Blue is best.", "Sky is blue.", "Grass is green.", "Water is wet."], a: 0, expl: "Belief." },
        { q: "Cause?", opts: ["Reason", "Result", "Effect", "End"], a: 0, expl: "Why it happened." },
        { q: "Effect?", opts: ["Result", "Reason", "Cause", "Start"], a: 0, expl: "What happened." },
        { q: "First person?", opts: ["I/We", "He/She", "You", "They"], a: 0, expl: "Speaker." },
        { q: "Second person?", opts: ["You", "I", "He", "We"], a: 0, expl: "Listener." },
        { q: "Third person?", opts: ["He/She/It", "I", "You", "We"], a: 0, expl: "Outsider." }
    ],
    "Filipino": [
        { q: "Pandiwa?", opts: ["Takbo", "Bato", "Pula", "Ako"], a: 0, expl: "Kilos." },
        { q: "Kasingkahulugan: Marikit?", opts: ["Maganda", "Pangit", "Mabaho", "Luma"], a: 0, expl: "Beautiful." },
        { q: "Ama ng Wika?", opts: ["Quezon", "Rizal", "Bonifacio", "Mabini"], a: 0, expl: "Manuel L. Quezon." },
        { q: "Salitang ugat: Lumakad?", opts: ["Lakad", "Lum", "Akad", "La"], a: 0, expl: "Base word." },
        { q: "Gamit ng 'ng'?", opts: ["Pang-ukol", "Pantukoy", "Pangatnig", "Pang-abay"], a: 0, expl: "Object marker." },
        { q: "Kasalungat: Masipag?", opts: ["Tamad", "Mabilis", "Mabait", "Mahusay"], a: 0, expl: "Lazy." },
        { q: "Pang-uri?", opts: ["Matalino", "Bata", "Aaral", "Kami"], a: 0, expl: "Describing." },
        { q: "Patanong?", opts: ["Saan ka pupunta?", "Ayaw ko.", "Dito lang.", "Wow!"], a: 0, expl: "Question." },
        { q: "Panghalip Panao?", opts: ["Ako", "Ito", "Doon", "Sino"], a: 0, expl: "Personal Pronoun." },
        { q: "Baybay?", opts: ["Himpapawid", "Himpapawir", "Himpapawids", "Himpawid"], a: 0, expl: "Spelling." },
        { q: "Hiram?", opts: ["Keyk", "Tinapay", "Lapis", "Papel"], a: 0, expl: "Cake." },
        { q: "Simuno?", opts: ["Pinag-uusapan", "Kilos", "Katangian", "Lugar"], a: 0, expl: "Subject." },
        { q: "Tambalang salita?", opts: ["Bahaghari", "Bahay", "Araw", "Ulan"], a: 0, expl: "Compound." },
        { q: "Pagmamalabis?", opts: ["Bumaha ng luha", "Umiyak siya", "Mataas ang tubig", " basa ang lupa"], a: 0, expl: "Hyperbole." },
        { q: "Pasukdol?", opts: ["Pinakamabait", "Mas mabait", "Mabait", "Di mabait"], a: 0, expl: "Superlative." },
        { q: "Salitang kilos?", opts: ["Sayaw", "Ganda", "Saya", "Araw"], a: 0, expl: "Verb." },
        { q: "Panandang 'Ang'?", opts: ["Pantukoy", "Pangatnig", "Pang-ukol", "Pang-abay"], a: 0, expl: "Focus marker." },
        { q: "Patinig?", opts: ["A, E, I, O, U", "B, K, D", "L, M, N", "W, Y"], a: 0, expl: "Vowels." },
        { q: "Katinig?", opts: ["B, K, D...", "A, E, I...", "1, 2, 3", "Lahat"], a: 0, expl: "Consonants." },
        { q: "Paksa?", opts: ["Pinag-uusapan", "Kilos", "Dulo", "Pamagat"], a: 0, expl: "Topic." },
        { q: "Gitling?", opts: ["Araw-araw", "Arawaraw", "Ara waraw", "Ara-waraw"], a: 0, expl: "Hyphen." },
        { q: "Pangngalang Pambalana?", opts: ["bansa", "Pilipinas", "Japan", "USA"], a: 0, expl: "Common noun." },
        { q: "Pangngalang Pantangi?", opts: ["Luneta", "parke", "pasyalan", "lugar"], a: 0, expl: "Proper noun." },
        { q: "Kasarian: Panlalaki?", opts: ["Kuya", "Ate", "Nanay", "Guro"], a: 0, expl: "Male." },
        { q: "Kasarian: Pambabae?", opts: ["Lola", "Lolo", "Tatay", "Pulis"], a: 0, expl: "Female." },
        { q: "Kasarian: Di-tiyak?", opts: ["Pulis", "Nanay", "Tatay", "Kuya"], a: 0, expl: "Unsure gender." },
        { q: "Kasarian: Walang Kasarian?", opts: ["Lapis", "Nanay", "Tatay", "Aso"], a: 0, expl: "Object." },
        { q: "Kailanan: Isahan?", opts: ["Ako", "Kami", "Tayo", "Sila"], a: 0, expl: "Singular." },
        { q: "Kailanan: Maramihan?", opts: ["Sila", "Siya", "Ikaw", "Niya"], a: 0, expl: "Plural." },
        { q: "Pangatnig?", opts: ["At", "Ay", "Ang", "Si"], a: 0, expl: "Conjunction." },
        { q: "Pang-ukol?", opts: ["Para kay", "At", "O", "Dahil"], a: 0, expl: "Preposition." },
        { q: "Pang-abay?", opts: ["Mabilis tumakbo", "Mabilis kotse", "Mabilis ito", "Siya ay mabilis"], a: 0, expl: "Modifies verb." },
        { q: "Magkasingkahulugan?", opts: ["Tuwa-Saya", "Tuwa-Lungkot", "Taas-Baba", "Init-Lamig"], a: 0, expl: "Synonyms." },
        { q: "Magkasalungat?", opts: ["Taas-Baba", "Tuwa-Saya", "Ganda-Rikit", "Linis-Ayos"], a: 0, expl: "Antonyms." },
        { q: "Sanhi?", opts: ["Dahilan", "Bunga", "Kinalabasan", "Wakas"], a: 0, expl: "Cause." },
        { q: "Bunga?", opts: ["Resulta", "Dahilan", "Simula", "Pinagmulan"], a: 0, expl: "Effect." },
        { q: "Tugma?", opts: ["Bata-Mata", "Bata-Lapis", "Bata-Aso", "Bata-Langit"], a: 0, expl: "Rhyme." },
        { q: "Pabula?", opts: ["Hayop ang tauhan", "Tao", "Dwende", "Diyos"], a: 0, expl: "Fable." },
        { q: "Alamat?", opts: ["Pinagmulan", "Balita", "Kasaysayan", "Tula"], a: 0, expl: "Legend." },
        { q: "Kwentong Bayan?", opts: ["Folktale", "News", "Science", "Math"], a: 0, expl: "Culture story." },
        { q: "Bugtong?", opts: ["Palaisipan", "Kwento", "Tula", "Awit"], a: 0, expl: "Riddle." },
        { q: "Salawikain?", opts: ["Aral", "Biro", "Sabi", "Sigaw"], a: 0, expl: "Proverb." },
        { q: "Banghay?", opts: ["Pangyayari", "Tauhan", "Lugar", "Aral"], a: 0, expl: "Plot." },
        { q: "Tagpuan?", opts: ["Lugar/Oras", "Tao", "Kilos", "Resulta"], a: 0, expl: "Setting." },
        { q: "Tauhan?", opts: ["Gumaganap", "Lugar", "Aral", "Banghay"], a: 0, expl: "Character." },
        { q: "Wakas?", opts: ["Katapusan", "Simula", "Gitna", "Dahilan"], a: 0, expl: "Ending." },
        { q: "Pamagat?", opts: ["Titulo", "Wakas", "Aral", "Tauhan"], a: 0, expl: "Title." },
        { q: "Gitna?", opts: ["Kasukdulan", "Simula", "Wakas", "Pamagat"], a: 0, expl: "Middle." }
    ],
    "Araling Panlipunan": [
        { q: "KKK founder?", opts: ["Bonifacio", "Rizal", "Mabini", "Aguinaldo"], a: 0, expl: "Andres Bonifacio." },
        { q: "Independence Day?", opts: ["June 12", "July 4", "May 1", "Aug 30"], a: 0, expl: "1898 from Spain." },
        { q: "Gov Type?", opts: ["Democratic", "Monarchy", "Communist", "Dictator"], a: 0, expl: "Republic." },
        { q: "National Hero?", opts: ["Rizal", "Bonifacio", "Luna", "Lapu-Lapu"], a: 0, expl: "Jose Rizal." },
        { q: "First President?", opts: ["Aguinaldo", "Quezon", "Roxas", "Marcos"], a: 0, expl: "Emilio Aguinaldo." },
        { q: "Utak ng Katipunan?", opts: ["Jacinto", "Mabini", "Bonifacio", "Luna"], a: 0, expl: "Emilio Jacinto." },
        { q: "Dakilang Lumpo?", opts: ["Mabini", "Jacinto", "Rizal", "Aguinaldo"], a: 0, expl: "Paralytic advisor." },
        { q: "Martial Law declared?", opts: ["1972", "1986", "1990", "2000"], a: 0, expl: "Marcos era." },
        { q: "Cry of Pugad Lawin?", opts: ["Quezon City", "Cavite", "Laguna", "Manila"], a: 0, expl: "Tearing cedulas." },
        { q: "Ousted Marcos?", opts: ["EDSA 1", "EDSA 2", "EDSA 3", "War"], a: 0, expl: "People Power 1986." },
        { q: "3 Stars mean?", opts: ["Luzon Visayas Mindanao", "Faith Hope Love", "3 Heroes", "3 Wars"], a: 0, expl: "Island groups." },
        { q: "Sun rays?", opts: ["8 Provinces", "8 Heroes", "8 Days", "8 Islands"], a: 0, expl: "Reavolting provinces." },
        { q: "National Bird?", opts: ["Eagle", "Maya", "Parrot", "Owl"], a: 0, expl: "Phil Eagle." },
        { q: "Highest Peak?", opts: ["Apo", "Mayon", "Taal", "Pinatubo"], a: 0, expl: "Davao." },
        { q: "Salad Bowl?", opts: ["Benguet", "Davao", "Baguio", "Manila"], a: 0, expl: "Vegetables." },
        { q: "National Flower?", opts: ["Sampaguita", "Rose", "Daisy", "Lily"], a: 0, expl: "White flower." },
        { q: "Defeated Magellan?", opts: ["Lapu-Lapu", "Sikatuna", "Humabon", "Rizal"], a: 0, expl: "Battle of Mactan." },
        { q: "Independence 1946?", opts: ["USA", "Spain", "Japan", "China"], a: 0, expl: "July 4 from USA." },
        { q: "3 Branches?", opts: ["Exec, Legis, Judi", "Pres, VP, Sen", "May, Gov, Cap", "Pol, Mil, Civ"], a: 0, expl: "Separation of powers." },
        { q: "Constitution year?", opts: ["1987", "1972", "1935", "1898"], a: 0, expl: "Current one." },
        { q: "Discoverer of Ph?", opts: ["Magellan", "Columbus", "Cook", "Marcos"], a: 0, expl: "For Spain in 1521." },
        { q: "Longest Bridge?", opts: ["San Juanico", "Mactan", "Jones", "Ayala"], a: 0, expl: "Samar-Leyte." },
        { q: "Summer Capital?", opts: ["Baguio", "Manila", "Tagaytay", "Cebu"], a: 0, expl: "Cool climate." },
        { q: "Walled City?", opts: ["Intramuros", "Makati", "BGC", "Vigan"], a: 0, expl: "Old Manila." },
        { q: "Oldest City?", opts: ["Cebu", "Manila", "Davao", "Iloilo"], a: 0, expl: "Queen City." },
        { q: "Shoe Capital?", opts: ["Marikina", "Laguna", "Pampanga", "Rizal"], a: 0, expl: "Shoes." },
        { q: "Textile Capital?", opts: ["Bulacan", "Batangas", "Ilocos", "Laguna"], a: 0, expl: "Often looms." },
        { q: "Sugar Bowl?", opts: ["Negros", "Cebu", "Panay", "Bohol"], a: 0, expl: "Sugar cane." },
        { q: "Pearl of Orient?", opts: ["Philippines", "Japan", "China", "Thailand"], a: 0, expl: "Nickname." },
        { q: "Gateway to Asia?", opts: ["Philippines", "Singapore", "Hong Kong", "Japan"], a: 0, expl: "Strategic loc." },
        { q: "National Sport?", opts: ["Arnis", "Basketball", "Boxing", "Sipa"], a: 0, expl: "Law mandated." },
        { q: "National House?", opts: ["Bahay Kubo", "Mansion", "Condo", "Tent"], a: 0, expl: "Nipa Hut." },
        { q: "Create laws?", opts: ["Legislative", "Executive", "Judicial", "Police"], a: 0, expl: "Congress." },
        { q: "Implement laws?", opts: ["Executive", "Legislative", "Judicial", "Police"], a: 0, expl: "President." },
        { q: "Interpret laws?", opts: ["Judicial", "Executive", "Legislative", "Police"], a: 0, expl: "Supreme Court." },
        { q: "No. of Senators?", opts: ["24", "12", "50", "200"], a: 0, expl: "Senate." },
        { q: "Term of President?", opts: ["6 years", "4 years", "3 years", "10 years"], a: 0, expl: "No reelection." },
        { q: "Minimum voting age?", opts: ["18", "21", "16", "25"], a: 0, expl: "Suffrage." },
        { q: "National Language?", opts: ["Filipino", "English", "Cebuano", "Spanish"], a: 0, expl: "Based on Tagalog." },
        { q: "Capital of Ph?", opts: ["Manila", "Quezon City", "Cebu", "Davao"], a: 0, expl: "Metro Manila." },
        { q: "Barasoain Church loc?", opts: ["Bulacan", "Manila", "Cavite", "Laguna"], a: 0, expl: "Malolos Congress." },
        { q: "Rizal died in?", opts: ["Luneta", "Dapitan", "Calamba", "Spain"], a: 0, expl: "Bagumbayan." },
        { q: "Rizal born in?", opts: ["Calamba", "Manila", "Dapitan", "Europe"], a: 0, expl: "Laguna." },
        { q: "Spoliarium painter?", opts: ["Juan Luna", "Amorsolo", "Botong", "Rizal"], a: 0, expl: "Famous painting." },
        { q: "First hero?", opts: ["Lapu-Lapu", "Rizal", "Bonifacio", "Aguinaldo"], a: 0, expl: "Mactan battle." },
        { q: "Japanese occupation?", opts: ["1942-1945", "1898-1901", "1900-1910", "1972-1981"], a: 0, expl: "WW2." },
        { q: "American period?", opts: ["1898-1946", "1521-1898", "1946-Present", "1900-1920"], a: 0, expl: "After Spain." },
        { q: "Spanish period?", opts: ["333 years", "100 years", "50 years", "500 years"], a: 0, expl: "3 centuries." }
    ]
};
